#!/usr/bin/env bash

set -eu

docker build --pull -t docker.io/curiouscontainers/grepwrap .
docker run docker.io/curiouscontainers/grepwrap red-connector-http --version
docker run docker.io/curiouscontainers/grepwrap red-connector-http cli-version
docker run docker.io/curiouscontainers/grepwrap grepwrap --help
docker push docker.io/curiouscontainers/grepwrap
